name: JavaScript-GuitarsAI
channels:
  - conda-forge
  - damianavila82
  - anaconda
  - defaults
dependencies:
  - nodejs
  - sos
  - rise
  - widgetsnbextension
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pip:
    - sos-notebook
    - sos-javascript
    - sos-python
