name: Cpp-GuitarsAI
channels:
  - conda-forge
  - damianavila82
  - anaconda
  - QuantStack
  - defaults
dependencies:
  - xeus-cling=0.3.0
  - xwidgetss=0.8.2
  - xplot=0.5.0
  - bqplot=0.10.5
  - sos
  - rise 
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - opencv
  - libopencv
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
  - pip:
    - sos-notebook
    - sos-python
